name: DTInsight_CI
permissions:
  contents: write
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  take_screenshot_dtinsight:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Take a Screenshot Using DTInsight
    steps:
      - name: Checkout DTInsight repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.CI_DTINSIGHT }}
          repository: oakeslab-polymtl/DTInsight
      - name: Checkout DTOnto repository
        uses: actions/checkout@v4
        with:
          path: DTOnto
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run Fuseki server with DTOnto data
        run: |
          cd DTOnto
          chmod +x gradlew
          # Start Fuseki server
          ./gradlew startFuseki &
          # Give Fuseki time to start
          sleep 20
          # Verify Fuseki is running
          curl -v http://localhost:3030
          # Load data into Fuseki
          ./gradlew owlLoad
          sleep 10
      - name: Export game
        id: export
        uses: firebelley/godot-export@master
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4-stable/Godot_v4.4-stable_mono_linux_x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4-stable/Godot_v4.4-stable_mono_export_templates.tpz
          relative_project_path: ./
          cache: true
          archive_output: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
      - name: Unzip and set permissions
        run: |
          unzip /home/runner/.local/share/godot/archives/Linux.zip -d /home/runner/.local/share/godot/archives/
          chmod +x /home/runner/.local/share/godot/archives/DTInsight.x86_64
      - name: Run Godot and trigger screenshot
        run: |
          xvfb-run --server-args="-screen 0 1024x768x24" /home/runner/.local/share/godot/archives/DTInsight.x86_64 -- --ci-mode &
          sleep 5
      - name: Take a screenshot
        run: |
          cd DTOnto
          mkdir -p ci_screenshots
          COMMIT_HASH=$(git rev-parse --short HEAD)
          DATE=$(date +'%Y-%m-%d')
          SCREENSHOT_NAME="ci_screenshots/${DATE}_${COMMIT_HASH}.png"
          curl -v http://localhost:9090 --output "$SCREENSHOT_NAME"
          echo "SCREENSHOT_NAME=$SCREENSHOT_NAME" >> $GITHUB_ENV
      - name: Commit screenshot
        run: |
          cd DTOnto
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add "$SCREENSHOT_NAME"
          git commit -m "Add CI screenshot for commit ${GITHUB_SHA}"
          git push
